import type { Metadata } from "next";
import "./globals.css";
import Header from './components/Header';
import { ArrowBigUp } from 'lucide-react';
import { useEffect, useState } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [scrol, setScrol]= useState(false);
  
  const scrollFunction = () => {
    if (document.documentElement.scrollTop > 20) {
      setScrol(true);
    } else {
      setScrol(false);
    }
  };
    useEffect(() => {
      scrollFunction();
    }, []);
  
    window.onscroll = function () {
      scrollFunction();
    };
  
    const topFunction = () => {
      document.body.scrollTop = 0;
      document.documentElement.scrollTop = 0;
    };
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen overflow-x-hidden w-screen bg-lemon-chiffon dark:bg-dark-purple dark:text-platinum font-sans over">
          <div className=" min-h-screen">
            <button
              onClick={topFunction}
              id="myBtn"
              title="Go to top"
              className={`z-10 bottom-0 right-0 bg-raisin-black-300 hover:bg-raisin-black-600 text-lemon-chiffon dark:text-raspberry-rose dark:bg-platinum dark:hover:bg-celeste font-bold py-2 px-2 rounded-full mr-4 mb-4 ${
                scrol ? 'fixed' : 'hidden'
              }`}
            >
          <ArrowBigUp />
        </button>
      </div>
      <Header />
        {children}
        <footer className="flex justify-center opacity-75">
        <div>
          <p>By Doran Delfosse</p>
          <p className="text-center">© {(new Date().getFullYear())}</p>
        </div>
      </footer>
        </div>
      </body>
    </html>
  );
}
